# Generated by Django 3.1.7 on 2021-03-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_green', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('code', models.IntegerField(default=0)),
                ('brief', models.TextField(max_length=200)),
            ],
        ),
    ]
