# Generated by Django 3.1.7 on 2021-03-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_green', '0002_mission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='code',
        ),
    ]
