# Generated by Django 3.1.7 on 2021-03-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_green', '0003_remove_mission_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='points',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='controller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
